version: 2.1
jobs:
  sayhi:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - run:
            name: Just sends salutations
            command: echo "Hi everybody. Hope this works"
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run:
            name: Dependencies intallation for my app
            command: npm install
      - run:
            name: Running unit tests for the app
            command: npm test

# Workflows 
workflows:
  greet_and_build:
    jobs:
      - sayhi
      - build